version: '3'
services:
  db:
    image: postgres:10.4-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: .
    tty: true
    stdin_open: true
    command: bash -c "rm -f ./tmp/pids/server.pid && bundle exec foreman start -f Procfile.dev"
    environment:
      - RAILS_MASTER_KEY=0d51362a3d1bba258ef4668824fd159b
    volumes:
      - .:/app:cached
      - bundle_data:/usr/local/bundle
      - node_modules_data:/app/client/node_modules
    ports:
      # - "3000:3000"
      - "3001:3001"
    depends_on:
      - db

volumes:
  db_data:
  bundle_data:
  node_modules_data:

