version: '3'
services:
  db:
    image: postgres:10.4-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: .
    command: bundle exec foreman start -f Procfile.dev
    volumes:
      - .:/app:cached
      - bundle_data:/usr/local/bundle
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - db

volumes:
  db_data:
  bundle_data:
