version: 2.1

orbs:
  ruby: circleci/ruby@1.0.0
  node: circleci/node@3.0.0

jobs:
  build:
    docker:
      - image: cimg/ruby:2.6.5-node
    steps:
      - checkout
      - ruby/install-deps
    working_directory: ~/client
    steps:
      - node/install:
          node-version: '13.3.0'
      - run:
          name: Show node version
          command: node -v
      - run:
          name: Show npm version
          command: npm -v
      - node/install-packages

  test:
    docker:
      - image: cimg/ruby:2.6.5-node
    environment:
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test
    working_directory: ~/client
    steps:
      - node/install:
          node-version: '13.3.0'
      - node/install-packages
      - run:
          command: npm run test

workflows:
  version: 2
  build_and_test:     # The name of our workflow is "build_and_test"
    jobs:             # The list of jobs we run as part of this workflow.
      - build         # Run build first.
      - test:         # Then run test,
          requires:   # Test requires that build passes for it to run.
            - build   # Finally, run the build job.
